### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by wannaphong** [ErikGartner/sentimental#10]
I run cmd pip in windows 10. python 3.5 64bit

```
C:\>pip install sentimental
Collecting sentimental
  Downloading sentimental-2.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\B15D~1\AppData\Local\Temp\pip-build-l_rv6aoc\sentimental\setup.py", line 12, in <module>
        from version import __version__
    ImportError: No module named 'version'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\B15D~1\AppData\Local\Temp\pip-build-l_rv6aoc\sentimental\
```

**Comment by ghost** [comment]
The same error for me too

**Comment by SamirMatkar** [comment]
The same error for me too

**Comment by ttpro1995** [comment]
On Ubuntu 16.04, same issue

`pip install sentimental
`

```
Collecting sentimental
  Using cached sentimental-2.2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-v9x0t3wq/sentimental/setup.py", line 12, in <module>
        from version import __version__
    ModuleNotFoundError: No module named 'version'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-v9x0t3wq/sentimental/

```

**Comment by dutta14** [comment]
I am getting the same error.
